engine=PyTorch
option.modelName=all-MiniLM-L6-v2
option.mapLocation=true
padding=true
maxLength=256
includeTokenTypes=true
translatorFactory=ai.djl.huggingface.translator.TextEmbeddingTranslatorFactory
