engine=PyTorch
option.modelName=paraphrase-multilingual-MiniLM-L12-v2
option.mapLocation=true
padding=true
maxLength=128
normalize=false
includeTokenTypes=true
translatorFactory=ai.djl.huggingface.translator.TextEmbeddingTranslatorFactory
