apiVersion: v1
kind: Namespace
metadata:
  name: ai-search
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ai-search-es
  namespace: ai-search
spec:
  version: 8.13.4
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
        xpack.license.self_generated.type: basic
      podTemplate:
        spec:
          volumes:
            - name: user-dict
              configMap:
                name: es-user-dict
          containers:
            - name: elasticsearch
              volumeMounts:
                - name: user-dict
                  mountPath: /usr/share/elasticsearch/config/analysis/user_dict_ko.txt
                  subPath: user_dict_ko.txt
              resources:
                requests:
                  memory: 2Gi
                  cpu: "500m"
                limits:
                  memory: 2Gi
                  cpu: "2000m"
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms1g -Xmx1g"
