apiVersion: v1
kind: Namespace
metadata:
  name: ai-search
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ai-search-es
  namespace: ai-search
spec:
  version: 8.13.4
  image: __ES_IMAGE__
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
        xpack.license.self_generated.type: basic
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 2Gi
                  cpu: "500m"
                limits:
                  memory: 2Gi
                  cpu: "2000m"
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms1g -Xmx1g"
